### ISSUE TITLE
Design guide: Forms: .form-controls

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/wet-boew-styleguide#235]
In [bootstrap](http://getbootstrap.com/css/#forms-controls), the `.form-control` class is set to 100% 

but in WET we set it to:

``` css
.form-control {
  max-width: 100%;
  width: auto;
}
```

Curious why we are doing this. I need to add the `.full-width` for a textarea to but larger.
